# Generated by Django 5.2.11 on 2026-03-19 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_location', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RideOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=255)),
                ('to_location', models.CharField(max_length=255)),
                ('from_lat', models.FloatField(blank=True, null=True)),
                ('from_lng', models.FloatField(blank=True, null=True)),
                ('to_lat', models.FloatField(blank=True, null=True)),
                ('to_lng', models.FloatField(blank=True, null=True)),
                ('departure_time', models.DateTimeField()),
                ('seats_available', models.PositiveIntegerField(default=1)),
                ('price_per_seat', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
