# Generated by Django 5.2.11 on 2026-03-19 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_node_edge'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarpoolRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_requests', to='network.node')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpool_requests', to=settings.AUTH_USER_MODEL)),
                ('pickup_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_requests', to='network.node')),
            ],
        ),
        migrations.CreateModel(
            name='DriverOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detour_nodes', models.JSONField(default=list)),
                ('detour_distance', models.IntegerField(default=0)),
                ('fare', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carpool_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='trips.carpoolrequest')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_offers', to='trips.trip')),
            ],
        ),
        migrations.AddField(
            model_name='carpoolrequest',
            name='confirmed_offer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_for_request', to='trips.driveroffer'),
        ),
    ]
